clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 3597

    # The number of clients selected in each round
    per_round: 180

    # Should the clients compute test accuracy locally?
    do_test: false
    
    commu_simulation: true
    compute_comm_time: true

    speed_simulation: true
    max_sleep_time: 3
    simulation_distribution: 
        distribution: normal
        mean: 1
        sd: 0.5

    sample: uniform

server:
    address: 127.0.0.1
    port: 8010
    random_seed: 1
    simulate_wall_time: true
    do_test: true

data: 
    data_path: /data/dixi
    datasource: FEMNIST
    reload_data: true 
    concurrent_download: true 
    sampler: all_inclusive
    random_seed: 4

trainer:
    # The type of the trainer
    type: basic

    # The maximum number of training rounds
    rounds: 50

    # The maximum number of clients running concurrently
    max_concurrency: 30

    # The target accuracy
    target_accuracy: 0.95

    # The machine learning model
    model_name: lenet5

    # Number of epoches for local training in each communication round
    epochs: 5
    batch_size: 512
    optimizer: SGD

algorithm:
    # Aggregation algorithm
    type: fedavg

parameters:
    model:
        num_classes: 62
        
    optimizer:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0

results:
    result_path: /data/dixi/plato/results/ece1551